### ISSUE TITLE
Enhancement Request: eProcurement Error Notifications

### ISSUE THREAD

**Issue by nigelbrookes** [progressclaim/pc-roadmap#28]
Peter Jamieson @ Georgiou Group has asked if it is possible to generate a notification email for eProc claim sync errors as they appear in the reports/eprocurment claim sync page. 
Peter has said that this information can be easily missed during busy periods and a notification would help them resolve ERP related issues more quickly.

https://app.intercom.io/a/apps/fw34m5y4/respond/inbox/928590/conversations/11368286975

**Comment by alashin** [comment]
This is something that eProcurement is far better placed to do as it is the one that sets the invoice status so it has a trigger to then send an email in case of failure. For Progressclaim.com to do it we would have to start a polling process to monitor the status which is a bit more technical.

**Comment by nigelbrookes** [comment]
Thanks @alashin , I've referred the user back to their eProc team
